### ISSUE TITLE
Out of bounds error in BVH tree

### ISSUE THREAD

**Issue by allo-** [nmoehrle/libacc#2]
I get an out of bounds error at [bvh_tree.h#L267](https://github.com/nmoehrle/libacc/blob/dcf3b3e068352b38fb04109ef50ad4fc7bd57b38/bvh_tree.h#L267), with ``node.last == indices.size()``.

I guess this is a off by one error coming from somewhere else, but I do not see from where.

Currently I implemented a workaround to set ``node.last`` to ``indices.size()-1`` when its bigger, but I am not sure if this only changes the structure of the bounding volumes or if it changes the result.

**Comment by nmoehrle** [comment]
The second parameter to the sort function is an beyond the end iterator, so the off by one "access" in this case intentional. However, a more correct solution here, and in a couple of other places in this lib, would be `indices->begin() + node.last`. I am not sure when I'll have time to change that so I would be happy for a PR if you have the time ;-)

**Comment by allo-** [comment]
The problem is, that ``indices[node.last]`` is no iterator here, but a std::vector access, so it throws an exception. As far as I understand the code, you're accessing the last+1 element and then take the address (which probably is a pointer to the underlying array).

I will have look if ``indices.begin() + node.first, indices.begin()+node.last`` is the correct range for the iterator.

**Comment by nmoehrle** [comment]
I know that indices[node.last] would be an out of bounds access, but depending on the compiler you don't need to access an element to take its address. But after writing this I have to agree that the code is broken considering that it relies on a compiler "optimization".

**Comment by allo-** [comment]
I need to use MSVC here and it breaks.
But looking at it, it seems that std::sort uses the points like an iterator, because both "*it" and "it++" are working on pointers as on iterators, but probably it is not meant to work on something else than iterators.

**Comment by nmoehrle** [comment]
A pointer **is** an iterator, it is even a RandomAccessIterator since iterators are just concepts and a pointer implements all necessary functions to be classified as such. 

> A RandomAccessIterator is a BidirectionalIterator that can be moved to point to any element in constant time.
A pointer to an element of an array satisfies all requirements of RandomAccessIterator
http://en.cppreference.com/w/cpp/concept/RandomAccessIterator

Apart from that `&vec[idx]` is incorrect for (idx >= vec.size()) because it can be broken down to `&(vec[idx])`. I guess it never was an issue for me because the gcc stl has not bounds check on the array access operator and I never use the value of `vec[idx]` so the address of was optimized.

**Comment by allo-** [comment]
Fixed in #4
